// Code generated by protoc-gen-go. DO NOT EDIT.
// source: drlmcomm.proto

package drlmcomm

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Pass                 string   `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fc4245dea50b14b, []int{0}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *UserRequest) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

type SessionReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionReply) Reset()         { *m = SessionReply{} }
func (m *SessionReply) String() string { return proto.CompactTextString(m) }
func (*SessionReply) ProtoMessage()    {}
func (*SessionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fc4245dea50b14b, []int{1}
}

func (m *SessionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionReply.Unmarshal(m, b)
}
func (m *SessionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionReply.Marshal(b, m, deterministic)
}
func (m *SessionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionReply.Merge(m, src)
}
func (m *SessionReply) XXX_Size() int {
	return xxx_messageInfo_SessionReply.Size(m)
}
func (m *SessionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionReply.DiscardUnknown(m)
}

var xxx_messageInfo_SessionReply proto.InternalMessageInfo

func (m *SessionReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "drlmcomm.UserRequest")
	proto.RegisterType((*SessionReply)(nil), "drlmcomm.SessionReply")
}

func init() { proto.RegisterFile("drlmcomm.proto", fileDescriptor_3fc4245dea50b14b) }

var fileDescriptor_3fc4245dea50b14b = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x29, 0xca, 0xc9,
	0x4d, 0xce, 0xcf, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x4c,
	0xb9, 0xb8, 0x43, 0x8b, 0x53, 0x8b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8,
	0x58, 0x4a, 0x8b, 0x53, 0x8b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x90, 0x58,
	0x41, 0x62, 0x71, 0xb1, 0x04, 0x13, 0x44, 0x0c, 0xc4, 0x56, 0xd2, 0xe0, 0xe2, 0x09, 0x4e, 0x2d,
	0x2e, 0xce, 0xcc, 0xcf, 0x0b, 0x4a, 0x2d, 0xc8, 0xa9, 0x14, 0x92, 0xe0, 0x62, 0xcf, 0x4d, 0x2d,
	0x2e, 0x4e, 0x4c, 0x4f, 0x85, 0x6a, 0x85, 0x71, 0x8d, 0xfe, 0x30, 0x72, 0xb1, 0xbb, 0x14, 0xe5,
	0xe4, 0x3a, 0x16, 0x64, 0x0a, 0xd9, 0x70, 0x71, 0xfa, 0xe4, 0xa7, 0x67, 0xe6, 0x81, 0x6c, 0x14,
	0x12, 0xd5, 0x83, 0x3b, 0x0a, 0xc9, 0x05, 0x52, 0x62, 0x08, 0x61, 0x64, 0x1b, 0x94, 0x18, 0x84,
	0xac, 0xb8, 0xd8, 0x1d, 0x53, 0x52, 0xc8, 0xd6, 0xeb, 0x92, 0x9a, 0x43, 0x9e, 0x5e, 0x6b, 0x2e,
	0x0e, 0x9f, 0xcc, 0xe2, 0x12, 0xb2, 0x34, 0x27, 0xb1, 0x81, 0x03, 0xdc, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x2a, 0xbe, 0x91, 0x0a, 0x82, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DrlmApiClient is the client API for DrlmApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DrlmApiClient interface {
	LoginUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*SessionReply, error)
	AddUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*SessionReply, error)
	DelUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*SessionReply, error)
	ListUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*SessionReply, error)
}

type drlmApiClient struct {
	cc *grpc.ClientConn
}

func NewDrlmApiClient(cc *grpc.ClientConn) DrlmApiClient {
	return &drlmApiClient{cc}
}

func (c *drlmApiClient) LoginUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*SessionReply, error) {
	out := new(SessionReply)
	err := c.cc.Invoke(ctx, "/drlmcomm.DrlmApi/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drlmApiClient) AddUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*SessionReply, error) {
	out := new(SessionReply)
	err := c.cc.Invoke(ctx, "/drlmcomm.DrlmApi/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drlmApiClient) DelUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*SessionReply, error) {
	out := new(SessionReply)
	err := c.cc.Invoke(ctx, "/drlmcomm.DrlmApi/DelUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drlmApiClient) ListUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*SessionReply, error) {
	out := new(SessionReply)
	err := c.cc.Invoke(ctx, "/drlmcomm.DrlmApi/ListUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DrlmApiServer is the server API for DrlmApi service.
type DrlmApiServer interface {
	LoginUser(context.Context, *UserRequest) (*SessionReply, error)
	AddUser(context.Context, *UserRequest) (*SessionReply, error)
	DelUser(context.Context, *UserRequest) (*SessionReply, error)
	ListUser(context.Context, *UserRequest) (*SessionReply, error)
}

func RegisterDrlmApiServer(s *grpc.Server, srv DrlmApiServer) {
	s.RegisterService(&_DrlmApi_serviceDesc, srv)
}

func _DrlmApi_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrlmApiServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drlmcomm.DrlmApi/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrlmApiServer).LoginUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrlmApi_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrlmApiServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drlmcomm.DrlmApi/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrlmApiServer).AddUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrlmApi_DelUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrlmApiServer).DelUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drlmcomm.DrlmApi/DelUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrlmApiServer).DelUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrlmApi_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrlmApiServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drlmcomm.DrlmApi/ListUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrlmApiServer).ListUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DrlmApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "drlmcomm.DrlmApi",
	HandlerType: (*DrlmApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginUser",
			Handler:    _DrlmApi_LoginUser_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _DrlmApi_AddUser_Handler,
		},
		{
			MethodName: "DelUser",
			Handler:    _DrlmApi_DelUser_Handler,
		},
		{
			MethodName: "ListUser",
			Handler:    _DrlmApi_ListUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drlmcomm.proto",
}
